a = 100
print(a)
print("this is my first python program")
print("A","B","C")
print("A","B","C", sep="|")
print("A","B","C", sep="\t")
print("A","B","C", sep="\t",end=";;;;")
print("Hello")
print("Enter your first name: ")
firstName = input()
print("Hello, " + firstName + "!")
Print("Program Titles")